/*
 * Auto-generated by Frida. Please modify to match the signature of +[ume000 encryptData:aKey:lKey:isBase:].
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

{
  /**
   * Called synchronously when about to call +[ume000 encryptData:aKey:lKey:isBase:].
   *
   * @this {object} - Object allowing you to store state for use in onLeave.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {array} args - Function arguments represented as an array of NativePointer objects.
   * For example use args[0].readUtf8String() if the first argument is a pointer to a C string encoded as UTF-8.
   * It is also possible to modify arguments by assigning a NativePointer object to an element of this array.
   * @param {object} state - Object allowing you to keep state across function calls.
   * Only one JavaScript function will execute at a time, so do not worry about race-conditions.
   * However, do not use this to store function arguments across onEnter/onLeave, but instead
   * use "this" which is an object for keeping state local to an invocation.
   */
  onEnter: function (log, args, state) {
    log('+[ume000 encryptData:' + args[2] + ' aKey:' + args[3] + ' lKey:' + args[4] + ' isBase:' + args[5] + ']');
     console.log(hexdump(ptr(args[2].add(0x10).readPointer()), {
                length: 256,
                header: true,
                ansi: true
            }));

      console.log(hexdump(ptr(args[3]),     {
                  length: 128,
                  header: true,
                  ansi: true
              }));

      console.log(hexdump(ptr(args[4]),     {
                    length: 128,
                    header: true,
                   ansi: true
                }));
  },

  /**
   * Called synchronously when about to return from +[ume000 encryptData:aKey:lKey:isBase:].
   *
   * See onEnter for details.
   *
   * @this {object} - Object allowing you to access state stored in onEnter.
   * @param {function} log - Call this function with a string to be presented to the user.
   * @param {NativePointer} retval - Return value represented as a NativePointer object.
   * @param {object} state - Object allowing you to keep state across function calls.
   */
  onLeave: function (log, retval, state) {
     console.log(retval);
     console.log(hexdump(ptr(retval.add(0x10).readPointer()),     {
                    length: 128,
                    header: true,
                    ansi: true
                }));
  }
}
